"""Export short GIFs from MDBM's actual cell compositor for animated reference themes.

The GIFs are documentation artifacts only. No font files are distributed, and the
runtime remains the single mdbm.py source plus data-only .theme files.
"""
from __future__ import annotations
import html
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from render_support import ANIMATED_THEMES, scene

WIDTH, HEIGHT = 96, 32
FRAME_COUNT = 30
FRAME_MS = 125


def canvas_image(canvas):
    from PIL import Image, ImageDraw, ImageFont
    candidates = [
        (Path('/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'), Path('/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf')),
        (Path('C:/Windows/Fonts/consola.ttf'), Path('C:/Windows/Fonts/consolab.ttf')),
    ]
    fonts = next(((a, b) for a, b in candidates if a.exists() and b.exists()), None)
    if fonts is None:
        raise RuntimeError('No documentation-rendering monospace font found')
    normal = ImageFont.truetype(str(fonts[0]), 12)
    bold = ImageFont.truetype(str(fonts[1]), 12)
    cw, ch = 8, 16
    image = Image.new('RGB', (canvas.width * cw, canvas.height * ch), '#0b0d12')
    draw = ImageDraw.Draw(image)
    for y in range(canvas.height):
        for x in range(canvas.width):
            cell = canvas.cells[y * canvas.width + x]
            draw.rectangle((x*cw, y*ch, (x+1)*cw-1, (y+1)*ch-1), fill=cell.ink.bg or '#0b0d12')
    for y in range(canvas.height):
        for x in range(canvas.width):
            cell = canvas.cells[y * canvas.width + x]
            if cell.continuation:
                continue
            draw.text((x*cw, y*ch-1), cell.glyph, font=bold if cell.ink.bold else normal,
                      fill=cell.ink.fg or '#dce1e8')
            if cell.ink.underline:
                draw.line((x*cw, y*ch+13, (x+1)*cw-1, y*ch+13), fill=cell.ink.fg or '#dce1e8')
    return image


def main() -> None:
    out = Path(__file__).resolve().parents[1] / 'docs' / 'screenshots' / 'animated'
    out.mkdir(parents=True, exist_ok=True)
    pages = ['<!doctype html><html lang="en"><meta charset="utf-8">'
             '<meta name="viewport" content="width=device-width, initial-scale=1">'
             '<title>MDBM · animated compositor examples</title>'
             '<style>body{background:#0b0d12;color:#dce1e8;font:16px system-ui;margin:30px}'
             'p{max-width:78ch;color:#aab6c4}figure{margin:32px 0}img{max-width:100%;height:auto;border:1px solid #374052;image-rendering:auto}'
             'figcaption{margin:.5rem 0;color:#aab6c4}</style>'
             '<h1>MDBM / animated theme examples</h1>'
             '<p>These GIFs are generated from the actual MDBM cell compositor. Motion is theme data only; host controls, cursor, selection and dialogs remain protected. Each capture runs at 8 documentation frames per second, with a host cue injected halfway through.</p>']
    cue_for = {'maintenance-ecosystem':'save-success', 'relay-moth-swarm':'focus-change', 'diagnostic-aurora':'save-success'}
    with tempfile.TemporaryDirectory() as tmp:
        for theme in ANIMATED_THEMES:
            w, _ = scene(Path(tmp), theme, 'truecolour', WIDTH, HEIGHT)
            frames = []
            for i in range(FRAME_COUNT):
                t = i * FRAME_MS / 1000.0
                w.clock = t
                if i >= FRAME_COUNT // 2:
                    w.cue = cue_for[theme]
                    w.cue_time = (FRAME_COUNT // 2) * FRAME_MS / 1000.0
                else:
                    w.cue = 'startup'
                    w.cue_time = 0.0
                frames.append(canvas_image(w.frame(WIDTH, HEIGHT)))
            target = out / f'{theme}.gif'
            frames[0].save(target, save_all=True, append_images=frames[1:], duration=FRAME_MS,
                           loop=0, optimize=True, disposal=2)
            pages.append('<figure><img src="'+html.escape(target.name)+'" alt="Animated MDBM theme '+html.escape(w.theme.name)+'">'
                         '<figcaption><strong>'+html.escape(w.theme.name)+'</strong> · cue: '
                         +html.escape(cue_for[theme])+'</figcaption></figure>')
    pages.append('<p>Generated by <code>tests/render_animation_gallery.py</code>. Terminal font metrics and colour quantization can differ from these documentation captures.</p></html>')
    (out/'gallery.html').write_text(''.join(pages))
    print(out/'gallery.html')


if __name__ == '__main__':
    main()
