"""Export real composed cells as a static HTML gallery; optional PNGs need Pillow.
No JavaScript, ANSI output or font files are embedded in the exported artifacts.
"""
import html,sys,tempfile
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from render_support import GALLERY_THEMES,scene


def main():
    out=Path(__file__).resolve().parents[1]/'docs'/'screenshots';out.mkdir(parents=True,exist_ok=True)
    pieces=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>MDBM · actual cell renders</title><style>body{background:#0b0d12;color:#dce1e8;font:16px system-ui;margin:30px}h1{font-weight:650}p{max-width:75ch;color:#aab6c4}h2{margin-top:38px}pre{font:14px/18px "DejaVu Sans Mono",Consolas,monospace;white-space:pre;letter-spacing:0;display:inline-block;padding:0;margin:0;border:1px solid #374052}section{overflow:auto}small{color:#aab6c4}</style><h1>MDBM / Cell-native workspace</h1><p>Static snapshots of the actual compositor at 120 × 40 cells. This is not a browser version of the application. Seed, source, focus and animation time are fixed for comparison.</p>']
    with tempfile.TemporaryDirectory() as tmp:
        for theme in GALLERY_THEMES:
            w,canvas=scene(Path(tmp),theme,'truecolour',120,40)
            (out/(theme+'.txt')).write_text(canvas.plain()+'\n')
            pieces.append('<h2>'+html.escape(w.theme.name)+'</h2><section><pre>')
            for y in range(canvas.height):
                cells=canvas.cells[y*canvas.width:(y+1)*canvas.width]
                previous=None;chunk=[]
                def flush():
                    if not chunk:return
                    ink=previous
                    declarations=f'color:{ink.fg or "#dce1e8"};background:{ink.bg or "#0b0d12"}'
                    if ink.bold:declarations+=';font-weight:700'
                    if ink.italic:declarations+=';font-style:italic'
                    if ink.underline:declarations+=';text-decoration:underline'
                    if ink.strike:declarations+=';text-decoration:line-through'
                    pieces.append('<span style="'+declarations+'">'+html.escape(''.join(chunk))+'</span>')
                for cell in cells:
                    if cell.continuation:continue
                    if previous!=cell.ink:
                        flush();chunk=[];previous=cell.ink
                    chunk.append(cell.glyph)
                flush();pieces.append('\n')
            pieces.append('</pre></section>')
            try:
                from PIL import Image,ImageDraw,ImageFont
                fonts=[Path('/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'),Path('/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf')]
                if not all(p.exists() for p in fonts):continue
                normal,bold=(ImageFont.truetype(str(p),16) for p in fonts)
                cw,ch=10,21
                image=Image.new('RGB',(canvas.width*cw,canvas.height*ch),'#0b0d12');draw=ImageDraw.Draw(image)
                for y in range(canvas.height):
                    for x in range(canvas.width):
                        cell=canvas.cells[y*canvas.width+x]
                        draw.rectangle((x*cw,y*ch,(x+1)*cw-1,(y+1)*ch-1),fill=cell.ink.bg or '#0b0d12')
                for y in range(canvas.height):
                    for x in range(canvas.width):
                        cell=canvas.cells[y*canvas.width+x]
                        if cell.continuation:continue
                        draw.text((x*cw,y*ch-1),cell.glyph,font=bold if cell.ink.bold else normal,fill=cell.ink.fg or '#dce1e8')
                        if cell.ink.underline:draw.line((x*cw,y*ch+18,(x+1)*cw-1,y*ch+18),fill=cell.ink.fg or '#dce1e8')
                image.save(out/(theme+'.png'))
            except ImportError:pass
    pieces.append('<p><small>Generated by tests/render_gallery.py from MDBM-owned cell buffers. Terminal font rendering can differ. These are regression aids, not proof of native terminal compatibility.</small></p></html>')
    (out/'gallery.html').write_text(''.join(pieces))
    print(out/'gallery.html')

if __name__=='__main__':main()
